export const FEATURE_CATEGORIES = [
  "Build and collaboration",
  "Components",
  "Logic and workflow",
  "Integrations",
  "Analytics and reporting",
  "Authentication and access",
  "Security and compliance",
  "Governance and platform management",
  "Support and onboarding",
] as const;

export type FeatureCategory = (typeof FEATURE_CATEGORIES)[number];

export type DirectoryFeature = {
  name: string;
  description: string;
  category: FeatureCategory;
  plans: {
    businessCloud: boolean;
    businessEstate: boolean;
    institutional: boolean;
  };
};

const STANDARD = {
  businessCloud: true,
  businessEstate: true,
  institutional: true,
};

const INSTITUTIONAL = {
  businessCloud: false,
  businessEstate: false,
  institutional: true,
};

const feature = (
  name: string,
  description: string,
  category: FeatureCategory,
  plans = STANDARD,
): DirectoryFeature => ({ name, description, category, plans });

export const DIRECTORY_FEATURES: DirectoryFeature[] = [
  feature("WCAG 2.2 AA-supporting components", "Responsive components and patterns are designed to support WCAG 2.2 AA conformance. Final accessibility depends on each service’s content, configuration and implementation.", "Security and compliance"),
  feature("UK data residency options", "Store and process service data on UK-based infrastructure, subject to the selected plan and hosting model.", "Security and compliance"),
  feature("ISO 27001:2022-certified management system", "Govform.com operates an information security management system certified to ISO 27001:2022.", "Security and compliance"),
  feature("Cyber Essentials Plus certification", "Independently verified technical controls support protection against common cyber threats.", "Security and compliance"),
  feature("Drag-and-drop service builder", "Create pages, questions and complete service journeys in a visual no-code editor.", "Build and collaboration"),
  feature("Darcy AI Assistant", "Generate a structured service from a plain-English description, refine it conversationally and review changes before applying them.", "Build and collaboration"),
  feature("Multi-page service journeys", "Build services across multiple pages with navigation, service back links and progress indicators.", "Build and collaboration"),
  feature("Task-list pattern", "Guide users through sections of a complex service with clear completion and progress states.", "Components"),
  feature("Conditional page routing", "Show or skip pages based on user answers to create branching service journeys.", "Logic and workflow"),
  feature("Dynamic content display", "Show relevant questions, content and guidance in response to user input.", "Logic and workflow"),
  feature("Microsoft SharePoint lists and files", "Read from and write to SharePoint lists and document libraries during service workflows.", "Integrations"),
  feature("Microsoft Power Automate", "Trigger Power Automate flows when a submission is completed or reaches a configured workflow stage.", "Integrations"),
  feature("Configurable REST API client", "Connect to HTTP endpoints with configurable requests, responses, authentication, field mapping and Liquid payloads.", "Integrations"),
  feature("GOV.UK Notify email and SMS", "Send conditional confirmation emails and SMS messages through GOV.UK Notify.", "Integrations"),
  feature("Real-time service analytics dashboard", "Review starts, completions, drop-offs and service performance separately for QA and Production.", "Analytics and reporting"),
  feature("Page-level drop-off analysis", "Identify where users leave a journey and use validation-failure data to investigate friction.", "Analytics and reporting"),
  feature("Analytics without analytics cookies", "Collect unsampled service-usage data server-side without relying on analytics cookies.", "Analytics and reporting"),
  feature("Save and return", "Allow users to pause a service journey and resume it later using configurable draft modes.", "Logic and workflow"),
  feature("Multiple file uploads", "Accept multiple files with configurable limits, validation, review and file-type restrictions.", "Components"),
  feature("Antivirus scanning for uploads", "Scan supported uploaded files for malware before they enter storage or downstream workflows.", "Security and compliance"),
  feature("G-Cloud procurement route", "Procure eligible Govform.com services through the Crown Commercial Service G-Cloud framework.", "Support and onboarding"),
  feature("Crown Commercial Service supplier", "Access Govform.com through applicable Crown Commercial Service procurement arrangements.", "Support and onboarding"),
  feature("First-service build support", "Ask the Govform.com team to help configure an initial service as part of an agreed onboarding package.", "Support and onboarding"),
  feature("Excel and CSV lookup feeds", "Use refreshable Excel or CSV files as service lookup data, with separate sources by environment.", "Integrations"),
  feature("Govform.com REST API access", "Retrieve submissions and work with supported library resources programmatically using API credentials.", "Integrations"),
  feature("Microsoft Dataverse", "Connect service data to Dataverse tables for Microsoft Power Platform workflows.", "Integrations"),
  feature("Microsoft Power Apps connector", "Make service data available to Power Apps for operational applications and workflows.", "Integrations"),
  feature("Calculated fields", "Calculate values from answers and use the results in pages, logic, transformations and integrations.", "Logic and workflow"),
  feature("Data pre-population", "Pre-fill fields using earlier answers, session data or external API lookups.", "Logic and workflow"),
  feature("Document generation", "Generate formatted PDF documents from submitted service data.", "Logic and workflow"),
  feature("Field-level validation rules", "Apply configurable validation and provide specific, accessible error messages for individual fields.", "Logic and workflow"),
  feature("Liquid templating", "Use Liquid templates for dynamic content, conditional blocks, API payloads and email bodies.", "Logic and workflow"),
  feature("Multi-stage review workflows", "Configure sequential approvals, multi-party decisions, corrections, cancellation and withdrawal.", "Logic and workflow"),
  feature("Post-submission actions", "Trigger API requests, messages, SharePoint writes and Power Automate flows after submission.", "Logic and workflow"),
  feature("Repeating groups", "Capture multiple instances of a structured data set, such as addresses or household members.", "Logic and workflow"),
  feature("Service-to-service linking", "Connect related service journeys and pass approved data between them.", "Logic and workflow"),
  feature("Submission data API export", "Retrieve submission data through the API for case-management, reporting or business-intelligence systems.", "Analytics and reporting"),
  feature("Power BI reporting", "Feed submission data into Power BI for operational and management dashboards.", "Analytics and reporting"),
  feature("Submission reviewer", "Search, filter, sort, review and export submitted service data inside Govform.com.", "Analytics and reporting"),
  feature("Automatic language translation", "Offer supported service journeys in multiple languages while retaining their validation, logic and workflows.", "Build and collaboration"),
  feature("Responsive service layouts", "Deliver journeys that adapt across mobile, tablet and desktop screen sizes.", "Build and collaboration"),
  feature("Shareable prototype previews", "Share service prototypes with stakeholders for review before production deployment.", "Build and collaboration"),
  feature("Prototype, QA and Production environments", "Build, test and operate services in separate environments with controlled promotion between them.", "Governance and platform management"),
  feature("Version history and rollback", "Compare revisions and restore an earlier service version without losing the audit trail.", "Governance and platform management"),
  feature("UK postcode address lookup", "Find UK addresses from a postcode and map selected address lines into service fields.", "Components"),
  feature("Booking and calendar scheduling", "Let users select available dates or time slots and receive a booking confirmation.", "Components"),
  feature("Check-your-answers pages", "Present a pre-submission summary with links that let users review and change their answers.", "Components"),
  feature("Submission confirmation pages", "Show a configurable confirmation, reference number and clear next steps after submission.", "Components"),
  feature("Declarations and attestations", "Capture declarations with associated answers, signatures and audit information.", "Components"),
  feature("Maps and geolocation", "Let users select a location, capture coordinates and find nearby addresses through an interactive map.", "Components"),
  feature("Payment integrations", "Collect payments using GOV.UK Pay or supported third-party payment APIs.", "Components"),
  feature("Searchable results tables", "Present paginated results that authorised users can search and filter.", "Components"),
  feature("Shopping-cart and multi-item journeys", "Allow users to add and manage multiple items within a single service submission.", "Components"),
  feature("Spreadsheet-style data tables", "Capture repeating rows in configurable columns with validation for tabular data.", "Components"),
  feature("Private cloud or self-hosted deployment", "Deploy Govform.com into an agreed private-cloud or customer-controlled hosting environment.", "Security and compliance", INSTITUTIONAL),
  feature("Contracted disaster recovery", "Agree recovery-point and recovery-time objectives as part of an Institutional support arrangement.", "Governance and platform management", INSTITUTIONAL),
  feature("Cloud object-storage integrations", "Send uploaded files to AWS S3, Google Cloud Storage or Azure Blob Storage.", "Integrations"),
  feature("AWS SES email", "Send transactional service emails through AWS Simple Email Service.", "Integrations"),
  feature("Post-submission action alerts", "Notify an operational team when a configured API call or post-submission action fails.", "Integrations"),
  feature("Mutual TLS API authentication", "Use client certificates and mutual TLS to secure supported back-office API connections.", "Integrations"),
  feature("Mock API responses", "Test integrations with configured mock responses before connecting to live endpoints.", "Integrations"),
  feature("Integration architecture consultancy", "Work with Govform.com specialists on SharePoint, API and multi-system integration architecture.", "Support and onboarding", INSTITUTIONAL),
  feature("Enhanced support plan", "Add contracted response times, a dedicated support contact and agreed service-management arrangements.", "Support and onboarding", INSTITUTIONAL),
  feature("Platform audit event log", "Review recorded platform events including actions, errors, workflow decisions and administrative changes.", "Governance and platform management"),
  feature("AWS Well-Architected expertise", "Draw on architecture practices informed by the AWS Well-Architected Framework and partner expertise.", "Security and compliance"),
  feature("Encryption at rest", "Encrypt stored submission data, uploaded files and managed backups at rest.", "Security and compliance"),
  feature("Environment isolation", "Separate Prototype, QA and Production data, credentials and API connections.", "Security and compliance"),
  feature("ISO 9001:2015-certified quality system", "Govform.com operates a quality management system certified to ISO 9001:2015.", "Security and compliance"),
  feature("Regular penetration testing", "Use independent security testing to identify and address platform vulnerabilities.", "Security and compliance"),
  feature("TLS encryption in transit", "Protect data in transit using TLS 1.2 or later.", "Security and compliance"),
  feature("AWS Cognito authentication", "Use hosted Cognito user pools with configurable authentication and multi-factor controls.", "Authentication and access"),
  feature("Anonymous public access", "Publish services that users can complete without signing in.", "Authentication and access"),
  feature("Configurable session timeouts", "Set inactivity limits and show users an in-browser warning before sign-out.", "Authentication and access"),
  feature("Passwordless GOV.UK Notify sign-in", "Send a one-time sign-in link by email without requiring users to manage a password.", "Authentication and access"),
  feature("Group-based submission sharing", "Allow authorised members of a group to view and collaborate on shared submissions.", "Authentication and access"),
  feature("Multi-factor authentication enforcement", "Require supported users or administrators to complete an additional authentication factor.", "Authentication and access"),
  feature("OpenID Connect and OAuth 2.0", "Connect compatible identity providers, including Microsoft Entra ID and departmental single sign-on.", "Authentication and access"),
  feature("Read-only reviewer access", "Give staff, reviewers or caseworkers permission to view submissions without editing them.", "Authentication and access"),
  feature("99.9% availability target", "Use a production platform designed around a 99.9% availability target, subject to the applicable service agreement.", "Governance and platform management"),
  feature("Environment-specific secrets", "Keep production API keys and credentials separate from Prototype and QA values.", "Governance and platform management"),
  feature("Role-based platform access", "Assign granular administrative, build, QA, analytics and read-only permissions.", "Governance and platform management"),
  feature("Library-based organisation model", "Organise services into libraries that reflect teams, departments and access boundaries.", "Governance and platform management"),
  feature("Library-level MFA policies", "Require multi-factor authentication for users who access a selected service library.", "Governance and platform management"),
  feature("Managed backups", "Use automated backups for supported service data and configuration under the applicable service plan.", "Governance and platform management"),
  feature("Service duplication and migration", "Copy services between libraries to support reuse, restructuring and team migration.", "Governance and platform management"),
  feature("Brand configuration service", "Ask the Govform.com team to configure a theme that reflects your organisation’s agreed visual identity.", "Support and onboarding"),
  feature("Help centre and documentation", "Access product documentation, examples and practical guides for features and components.", "Support and onboarding"),
  feature("Proactive platform monitoring", "Monitor platform health and alert operational teams when service degradation is detected.", "Support and onboarding"),
  feature("UK-based live-service support", "Access support from a UK-based team through the channels included in your service agreement.", "Support and onboarding"),
  feature("Ordnance Survey Maps API", "Use licensed Ordnance Survey mapping and geographic reference data in supported UK location journeys.", "Integrations"),
  feature("Multi-party authorisation", "Require a configured number of reviewers, or every reviewer, to approve a workflow stage.", "Logic and workflow"),
  feature("Device and browser reporting", "Compare service usage and performance across device types, operating systems and browsers.", "Analytics and reporting"),
  feature("Tagged-field analytics", "Tag selected fields to analyse response patterns and the choices users make during a journey.", "Analytics and reporting"),
  feature("Validation-failure reporting", "Identify the fields that produce the most validation errors across service journeys.", "Analytics and reporting"),
  feature("Collaborative comments", "Add contextual comments to pages and review changes with multiple service collaborators.", "Build and collaboration"),
  feature("Custom CSS and Sass overrides", "Apply advanced stylesheet overrides for specialist branding and implementation requirements.", "Build and collaboration"),
  feature("Custom branding and themes", "Configure colours, typography, logos, headers and footers for a consistent service identity.", "Build and collaboration"),
  feature("Custom production domains", "Publish a service under an approved organisation or departmental domain.", "Build and collaboration"),
  feature("Reusable page templates", "Save and reuse pages, patterns and shared design-library elements across services.", "Build and collaboration"),
  feature("Accessible date input", "Capture day, month and year using an accessible date pattern with configurable validation.", "Components"),
];
